### ISSUE TITLE
Integrate with checks-api plugin

### ISSUE THREAD

**Issue by timja** [jenkinsci/junit-plugin#160]
This will allow publishing test results to GitHub checks

See https://github.com/jenkinsci/checks-api-plugin/blob/master/docs/consumers-guide.md

and https://github.com/jenkinsci/warnings-ng-plugin/pull/550

This should be updated in the JunitStep https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java

**Comment by timja** [comment]
cc @XiongKezhi in case you want to add anything

**Comment by XiongKezhi** [comment]
LGTM now. I can help with it after this hiring season if nobody is still interested in it by then.

**Comment by KalleOlaviNiemitalo** [comment]
FYI, I filed [JENKINS-64714](https://issues.jenkins.io/browse/JENKINS-64714) requesting a similar feature in the [xUnit plugin](https://plugins.jenkins.io/xunit/).
