### ISSUE TITLE
Version 1.36 not found

### ISSUE THREAD

**Issue by fabricat** [jenkinsci/junit-plugin#168]
When trying to update the plugin, Jenkins fails because this resuorce is not found (error 404): https://get.jenkins.io/plugins/junit/1.36/junit.hpi

**Comment by ankithriday** [comment]
I double on this, This is causing Jenkins failure `https://updates.jenkins.io/dynamic-2.248/latest/junit.hpi` directs it to `https://get.jenkins.io/plugins/junit/1.36/junit.hpi` which doesn't exist.

**Comment by rbankole** [comment]
logs from curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/2.235/latest/junit-plugin.hpi -o /usr/share/jenkins/ref/plugins/junit-plugin.jpi
curl: (22) The requested URL returned error: 404 Not Found

**Comment by rbankole** [comment]
We're using jenkins casc via helm chart. I fixed this issue by overriding the plugins with entry in the **master.installPlugins** section of my values.yaml file. 

ie - 
installPlugins:
  - junit:1.35

**Comment by timja** [comment]
I’ll be fixing this soon, the Jenkins infra job broke yesterday morning, all the plugins released yesterday are unavailable, it was fixed late last night EU time for new releases of plugins

**Comment by timja** [comment]
Fixed now
