### ISSUE TITLE
Custom names per junit invocation

### ISSUE THREAD

**Issue by mrginglymus** [jenkinsci/junit-plugin#183]
We're using (and loving) this new usage of the checks API for junit. However, we have multiple invocations of junit (across multiple different pipelines jobs) per PR.

This means that currently, only the last reported test appears. Is there something in the works to allow for custom names? I'm happy to try to contribute myself if not.

**Comment by timja** [comment]
Hi, no there currently isn't a way, but it should be quite easy to add.

maybe
freestyle:

Checks name: 'Tests'

pipeline:
`checksName:`

and just have it default to tests and allow you to override and set whatever you like?

Happy to take a PR for it :heart:

**Comment by mrginglymus** [comment]
Great, I'll have a play next week 👍

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/junit-plugin/pull/189
