### ISSUE TITLE
Checks API limit

### ISSUE THREAD

**Issue by timja** [jenkinsci/junit-plugin#192]
need to trim the characters we send to checks API (65535) is the limit:

```
[2020-10-23T15:02:30.961Z] [GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/jenkinsci/jenkins/check-runs {"message":"Invalid request.\n\nOnly 65535 characters are allowed; 569338 were supplied.","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

Needs to be shortened here ish https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java#L76

**Comment by timja** [comment]
fixed by https://github.com/jenkinsci/junit-plugin/pull/193

**Comment by KalleOlaviNiemitalo** [comment]
The 65535-character limit seems to be specific to GitHub.

* GitLab: I did not find a checks API as such. [Post the build status to a commit](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit) supports a "short description". [Create new merge request note](https://docs.gitlab.com/ee/api/notes.html#create-new-merge-request-note) has a limit of 1,000,000 characters. [Unit test reports](https://docs.gitlab.com/ee/ci/unit_test_reports.html) reads JUnit reports from build artifacts.
* Bitbucket Server: The details string of a Code Insights report is at most 2000 characters; likewise the message string of each annotation in the report. [REST Resources Provided By: Bitbucket Server - Code Insights](https://docs.atlassian.com/bitbucket-server/rest/7.7.0/bitbucket-code-insights-rest.html)
* Bitbucket Cloud: Maximum lengths of strings in Code Insights are not documented. [PUT /2.0/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bcommit%7D/reports/%7BreportId%7D#put), [PUT /2.0/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations/{annotationId}](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bcommit%7D/reports/%7BreportId%7D/annotations/%7BannotationId%7D#put)

So, this may have to be revisited when Checks API is implemented for systems other than GitHub.
