### ISSUE TITLE
Allow old test reports

### ISSUE THREAD

**Issue by ZakTaccardi** [jenkinsci/junit-plugin#201]
I'm seeing an incorrect error:

```
Recording test results
Test reports were found but none of them are new. Did leafNodes run? 

For example, /home/tools/jenkins/workspace/../mySdk/build/test-results/testDebugUnitTest/TEST-com.example.ExampleTest.xml is 16 hr old
```

This is correct, because I am using Gradle and it has identified that it did not need to execute the tests because it was previously run and no inputs have changed from a previous build

Some of my code:

```groovy
@Field String jUnitReports = [
        '**/build/test-reports/*.xml',
        '**/build/test-results/**/*.xml',
        '**/build/outputs/androidTest-results/**/*.xml',
        '**/spoon-output/**/junit-reports/*.xml',
        '**/junit-reports/*.xml',
        '**/build/outputs/androidTest-results/**/*.xml',
]
        .join(",")
```

```groovy
post {
  always { 
    junit testResults: jUnitReports, allowEmptyResults: true
}
```

Can a flag be added to allow old test reports and skip this check? Maybe `allowOldTestReports: true`?

Note: currently using JUnit Plugin version 1.28

Relates to:
- https://issues.jenkins-ci.org/browse/JENKINS-47315
- https://issues.jenkins-ci.org/browse/JENKINS-6268
- https://github.com/jenkinsci/junit-plugin/pull/108

**Comment by timja** [comment]
There's a PR for it here: https://github.com/jenkinsci/junit-plugin/pull/108

**Comment by mpress** [comment]
> There's a PR for it here: #108

A PR that is over two years old :(

**Comment by pappnase99** [comment]
I'm seeing the same error, although my test results are only "11 sec old". Test is flaky, sometimes successful, but mostly failing. No idea what to do, the related PR is closed.

**Comment by liyaka** [comment]
we are in 2022 and still the same problem - is there anything that can be done??

**Comment by timja** [comment]
submit a PR for it?

**Comment by timja** [comment]
Also having someone tell me:

> so do it yourself

Is a great way to have this drop to the bottom of my priorities =/

**Comment by Yohandah** [comment]
I think rejecting 2 PR fixing this issue and the fact it's been 4 years: it's already at the bottom of ur list ! It doesn't encourage ppl to contribute either. 
No worries, there's workarounds

**Comment by jtnord** [comment]
NB: could be reverted as this changes the behaviour of the plugin from reporting tests that ran to any test there is a report for.
To be replaced by something more like the original suggestion that allows you to opt-in to the behaviour of reporting anything that exists.
#367
