### ISSUE TITLE
mvn enforcer preventing build

### ISSUE THREAD

**Issue by jvezinat** [jenkinsci/junit-plugin#208]
Untarred source for 1.4.3 using maven 3.0.5 on RHEL 7.  Java 1.8.0_722.  When i run "mvn install" i get the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (display-info) on project junit: A type incompatibility occured while executing org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession

I have not edited the existing pom.xml in any way.

 mvn --version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_272, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.2.1.el7.x86_64", arch: "amd64", family: "unix"

Anything i can check? Is this a maven issue?

**Comment by timja** [comment]
please use a more recent version of maven, we build with 3.6.1 I believe

**Comment by jvezinat** [comment]
Yup, i was about to reply i just found the issues with switch from eclipse to aether in 3.0.5.  My apologies for raising an issue,  Thanks for reply!
