### ISSUE TITLE
Missing summary in check when no test results recorded

### ISSUE THREAD

**Issue by jglick** [jenkinsci/junit-plugin#221]
Not sure if this is related to #211. 
![test-results](https://user-images.githubusercontent.com/154109/101165167-3280c100-3604-11eb-8594-345ff073a1a1.png)
https://github.com/jenkinsci/bom/runs/1498792384 and all other plugin branches show no test result count. Only the initial https://github.com/jenkinsci/bom/runs/1498759937 displays

> **passed: 8**

as expected.

**Comment by jglick** [comment]
(I do not consider this particularly important, unless test _failures_ are not reported either. Have not yet observed an unstable build to check.)

**Comment by mrginglymus** [comment]
I'm seeing test result counts on most runs except durable task and echarts. Currently stuck under toddler and wrangling GitHub's very limited app, so hard to see exactly what's gone on.

**Comment by mrginglymus** [comment]
![image](https://user-images.githubusercontent.com/390569/101172329-f156d400-3638-11eb-8912-1b6d227e1a8e.jpeg)

**Comment by timja** [comment]
ah interesting, I expect this will trigger some failures: https://github.com/jenkinsci/bom/pull/376

**Comment by mrginglymus** [comment]
💥

**Comment by jglick** [comment]
So we do get details on failures; it is only the count which is missing on subsequent checks.

**Comment by mrginglymus** [comment]
Everything looks ok to me - iirc you don’t get a count when there’s a single failure, right? And the greens with no counts also didn’t have any tests.

That’s definitely something to improve though, to explicitly say ‘no tests found’ rather than not show a count

**Comment by jglick** [comment]
> the greens with no counts also didn’t have any tests

Ah, missed that in https://github.com/jenkinsci/bom/runs/1498880553 for example. (https://github.com/jenkinsci/bom/pull/341 means that this was common, for plugins including no explicit tests.) Maybe better to just omit the check altogether if there were no tests (when `allowEmptyResults: true`)?

**Comment by mrginglymus** [comment]
Yes - I suppose once you’ve set that `true` you shouldn’t be surprised if you get no results :)

**Comment by timja** [comment]
Possibly just put in the summary:

> No test results found

?

A little bit weary of omitting but also could be a valid solution

**Comment by mrginglymus** [comment]
That would be my preference but I’ve never used ‘allow empty results’ so can’t speak from experience.

Doesn’t seem worth adding another config...

**Comment by timja** [comment]
> Doesn’t seem worth adding another config...

agree
