### ISSUE TITLE
Can not add html tags in junit xml 

### ISSUE THREAD

**Issue by bearxc** [jenkinsci/junit-plugin#254]
I tried to add  a  html link inside a  junit  xml file  , it seems  all those tags  can not be populated in jenkins report .

[a.txt](https://github.com/jenkinsci/junit-plugin/files/6080247/a.txt)

**Comment by timja** [comment]
For good reason? then you could have script tags and XSS attacks on your users

**Comment by bearxc** [comment]
> I tried to add a html link inside a junit xml file as following , it seems "[google](http://www.google.com)" can not be populated in jenkins report .
> 
> html tag [google](http://www.google.com)

**Comment by bearxc** [comment]
Is it possible to make it optional ?

I want to add test case/bug link inside report
