### ISSUE TITLE
Dislable the unstable status

### ISSUE THREAD

**Issue by nroose** [jenkinsci/junit-plugin#278]
### Feature Request

We are using this with rspec in jenkins jobs and we want to prevent the result from being changed from success to unstable based on retries - we run rspec with `--only-failures` if the rspec run fails the first time. We have an old, large rails project with 10,000 specs and there are often some tests that fail. We have other ways to track, prioritize, and manage those. I tried setting the amplification to 0, but that does not seem to do it. Is there some other way to prevent this already?

**Comment by haydarAlaeddin** [comment]
you could manipulate the job result from your pipeline script, doing something like:
```
      if (currentBuild.result == 'UNSTABLE') {
        currentBuild.rawBuild.@result = hudson.model.Result.SUCCESS
      }
```
Check https://stackoverflow.com/questions/38221836/how-to-manipulate-the-build-result-of-a-jenkins-pipeline-job-back-to-success

**Comment by nroose** [comment]
We're currently using a declarative pipeline, rather than a scripted one.

**Comment by nroose** [comment]
Can't seem to figure out how we would do this in our environment. We have a pipeline that runs other jobs using the build line in a declarative pipeline... I am not sure I would redo everything to see if this would work, or for this purpose alone.
