### ISSUE TITLE
Test view table has broken dropdowns

### ISSUE THREAD

**Issue by josephjthomas** [jenkinsci/junit-plugin#344]
### Jenkins and plugins versions report

Jenkins 2.332, JUnit plugin 1.53

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Linux - 3.10.0-1160.45.1.el7.x86_64

### Reproduction steps

1. Install the JUnit plugin
2. Archive tests for a project that has JUnit tests
3. Head to the `/testReport/` tab of a build

### Expected Results

I am not sure which kind of information used to be displayed here, maybe it would make sense to remove the drop down button overall to avoid confusion.

### Actual Results

All tests have a non working dropdown. The same applies to the `/testReport/history/` tab.
![](https://i.imgur.com/ywhwQyc.png)

**Comment by timja** [comment]
PR that fixes it is up at https://github.com/jenkinsci/junit-plugin/pull/345, I've asked a couple of people if they know if it's supposed to be used for something
