### ISSUE TITLE
1.55 requires Jenkins (2.321) or higher which breaks Jenkins LTS installation

### ISSUE THREAD

**Issue by ayanamist** [jenkinsci/junit-plugin#354]
### Jenkins and plugins versions report

Jenkins 2.319.3

### What Operating System are you using (both controller, and any agents involved in the problem)?

All

### Reproduction steps

1. Install Jenkins 2.319.3 which is the latest LTS version
2. Through first init wizard, install JUnit plugin or any other plugin dependent on it

### Expected Results

Install success

### Actual Results

Install fail with
jenkins    | 2022-02-16 10:08:43.840+0000 [id=95]       SEVERE  h.model.UpdateCenter$DownloadJob#run: Failed to install junit
jenkins    | java.io.IOException: Failed to load: JUnit Plugin (1.55)
jenkins    |  - Jenkins (2.321) or higher required
jenkins    |    at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
jenkins    |    at hudson.PluginManager.dynamicLoad(PluginManager.java:917)

### Anything else?

I see this break change happens on 1.55 only which bump dependency for only a small change. But init wizard won't use 1.54, so i must manually copy the hpi into plugin directory and restart the jenkins process and init wizard, which is quit annoying.

**Comment by timja** [comment]
Please report to https://github.com/jenkins-infra/helpdesk.

The infra is designed to give you a valid version and if it's not then that's nothing to do with the JUnit plugin
