### ISSUE TITLE
plugin reports all existing tests, not tests that ran

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/junit-plugin#368]
### Jenkins and plugins versions report

the plugin now reports all tests, and not just tests that run in the build.

https://github.com/jenkinsci/junit-plugin/pull/348#issuecomment-1072274140

### What Operating System are you using (both controller, and any agents involved in the problem)?

all

### Reproduction steps

Build a project
wait an hour
delete all the tests
build the project again (in the same agent with the same workspace)

### Expected Results

no test results are reported as no tests ran

### Actual Results

all the tests that that previously ran reported.

**Comment by lppedd** [comment]
Hi @jtnord! Any workaround for us fellas that are still on older releases of Jenkins/plugin?
