### ISSUE TITLE
What is the configurations to get Junit plugin to show test result in hierarchy structure?

### ISSUE THREAD

**Issue by quad5** [jenkinsci/junit-plugin#378]
So I have 3 report files testing the same test case but in different view mode (ie desktop, mobile, and tablet). What is the configurations to get Junit plugin to show test result in hierarchy structure?

For example:
Test suite name (Desktop View) -> File name->  Test case
Test suite name (Mobile View) -> File name -> Test case
Test suite name (Tablet View) -> File name ->  Test case

<img width="1195" alt="Untitled1" src="https://user-images.githubusercontent.com/2043287/165197600-1eecbc8f-c763-42d3-941a-25654b2fe4a1.png">
<img width="1341" alt="Untitled2" src="https://user-images.githubusercontent.com/2043287/165197604-0a864e8c-b033-4174-b115-8ed7fdb348d5.png">

Junit version: 1.29
Jenkins version: 2.260

**Comment by zztalker** [comment]
If classname in Junit report will be in "package.class" format it will be grouped by package, then class.

In your case you need to add "DeskTop_View.C105260...." to classname attribute of each testcase.
