### ISSUE TITLE
Linking to test view from main job view uses wrong redirect

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/junit-plugin#486]
### Jenkins and plugins versions report

https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

1. Navigate to https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/316/
2. Click on the "Test Result Trend" graph
3. Get redirected to https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/316/test/ (316 is interchangeable with the latest build number/the build number you click on at the graph)
4. You are redirected to https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/316/ immediately without doing anything.
5. Navigate manually to the test overview.

### Expected Results

Clicking on the test graph should take you to https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/316/testReport/, rather than https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/master/316/test/

`testReport` instead of `test` is the notable difference.

### Actual Results

See reproduction steps.

**Comment by uhafner** [comment]
Duplicate, see https://issues.jenkins.io/browse/JENKINS-64582
