### ISSUE TITLE
Allow old test reports via configuration

### ISSUE THREAD

**Issue by Phenix66** [jenkinsci/junit-plugin#590]
### What feature do you want to see added?

When using a build system such as Gradle that supports caching, build tasks may be skipped if they are considered up to date (i.e. no source code changes). It would be nice to have a configurable option on this plugin to allow for the reports that junit considers out of date to be parsed anyways. At the moment, I am forced to re-run all of my tests in the pipeline and cannot use the "Restart from stage" feature of Jenkins if the stage it failed at was after my tests.

Note: I am not suggesting considering them empty results or to be skipped, I have read through those past issues and PRs already. I would want the test results to be considered valid if a configuration option was set, e.g. `allowOldTimestamps: true`.

**Comment by timja** [comment]
Doesn't it already do that?

If the test reports are there they will be parsed.

See some changes in this area:
https://github.com/jenkinsci/junit-plugin/pull/384

**Comment by Phenix66** [comment]
I read through that PR and it seemed like that was the original intent as the configuration keyword was `parseOldReports` but then that was changed later in the PR to `skipOldReports`. It's extra confusing though because a help HTML file was left with the `parseOldReports` naming.

The change in this file specifically indicates that it will skip parsing old reports though: https://github.com/jenkinsci/junit-plugin/pull/384/files#diff-90239b93606f793d1955a298da47f953f4fc053ebb9feb6c4a09970d719dc65d

**Comment by timja** [comment]
Yes so it defaults to parsing old reports. which is what you want I think?

**Comment by Phenix66** [comment]
Yes, it is. My apologies, I think I misunderstood something from that PR. I thought the new flag created 2 scenarios:

1. Old test results are present and `skipOldReports` is false, resulting in an error regarding the timestamps being old
2. Old test results are present and `skipOldReports` is true, resulting in the old tests being skipped.

I see now that my understanding of scenario 1 may be incorrect. Thank you for the responses.
