### ISSUE TITLE
i can't remove JUnit Plugin

### ISSUE THREAD

**Issue by nhanai777** [jenkinsci/junit-plugin#647]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows 

### Reproduction steps

<img width="652" alt="Screenshot_1" src="https://github.com/user-attachments/assets/0df264a1-9f38-4522-a664-a683d97b07b5">

### Expected Results

can remove plugin

### Actual Results

can't remove

**Comment by timja** [comment]
This isn't a bug in the plugin, please use https://community.jenkins.io for help with using Jenkins
